//===----------------------------------------------------------------------===//
//                         DuckDB
//
// function/scalar/dependent_functions.hpp
//
//
//===----------------------------------------------------------------------===//
// This file is automatically generated by scripts/generate_functions.py
// Do not edit this file manually, your changes will be overwritten
//===----------------------------------------------------------------------===//

#pragma once

#include "duckdb/function/function_set.hpp"

namespace duckdb {

struct ArrayTypeFun {
	static constexpr const char *Name = "array_type";
	static constexpr const char *Parameters = "type,int";
	static constexpr const char *Description = "Creates an array of the specified type and length, filled with NULLs.";
	static constexpr const char *Example = "array_type('int', 3)";
	static constexpr const char *Categories = "array";

	static ScalarFunction GetFunction();
};

struct ArrayJoinFun {
	static constexpr const char *Name = "array_join";
	static constexpr const char *Parameters = "array,...";
	static constexpr const char *Description = "Concatenates arrays. `NULL` inputs are skipped. See also operator `||`.";
	static constexpr const char *Example = "array_concat([2, 3], [4, 5, 6], [7])";
	static constexpr const char *Categories = "array";

	static ScalarFunction GetFunction();
};

} // namespace duckdb
