//===----------------------------------------------------------------------===//
//                         DuckDB
//
// function/scalar/geometry_functions.hpp
//
//
//===----------------------------------------------------------------------===//
// This file is automatically generated by scripts/generate_functions.py
// Do not edit this file manually, your changes will be overwritten
//===----------------------------------------------------------------------===//

#pragma once

#include "duckdb/function/function_set.hpp"

namespace duckdb {

struct StExtentFun {
	static constexpr const char *Name = "st_extent";
	static constexpr const char *Parameters = "geometry";
	static constexpr const char *Description = "Returns the extent of a geometry";
	static constexpr const char *Example = "st_extent(geometry)";
	static constexpr const char *Categories = "";

	static ScalarFunction GetFunction();
};

struct StIntersectExtentFun {
	static constexpr const char *Name = "st_intersect_extent";
	static constexpr const char *Parameters = "geometry,geometry";
	static constexpr const char *Description = "Returns if two geometries extents intersect";
	static constexpr const char *Example = "st_intersect_extent(geometry)";
	static constexpr const char *Categories = "";

	static ScalarFunctionSet GetFunctions();
};

struct StIntersectExtentFunAlias {
	using ALIAS = StIntersectExtentFun;

	static constexpr const char *Name = "&&";
};

struct StCrsFun {
	static constexpr const char *Name = "st_crs";
	static constexpr const char *Parameters = "geometry";
	static constexpr const char *Description = "Returns the coordinate reference system of a geometry type";
	static constexpr const char *Example = "st_crs(geometry)";
	static constexpr const char *Categories = "";

	static ScalarFunctionSet GetFunctions();
};

struct StGeomfromwkbFun {
	static constexpr const char *Name = "st_geomfromwkb";
	static constexpr const char *Parameters = "wkb";
	static constexpr const char *Description = "Creates a GEOMETRY from a WKB (Well-Known Binary) representation";
	static constexpr const char *Example = "st_geomfromwkb(wkb)";
	static constexpr const char *Categories = "";

	static ScalarFunctionSet GetFunctions();
};

struct StGeogfromwkbFun {
	static constexpr const char *Name = "st_geogfromwkb";
	static constexpr const char *Parameters = "ewkb";
	static constexpr const char *Description = "Creates a GEOGRAPHY from an WKB (Well-Known Binary) representation";
	static constexpr const char *Example = "st_geogfromewkb(ewkb)";
	static constexpr const char *Categories = "";

	static ScalarFunctionSet GetFunctions();
};

} // namespace duckdb
