//===----------------------------------------------------------------------===//
//                         DuckDB
//
// function/scalar/geometry_functions.hpp
//
//
//===----------------------------------------------------------------------===//
// This file is automatically generated by scripts/generate_functions.py
// Do not edit this file manually, your changes will be overwritten
//===----------------------------------------------------------------------===//

#pragma once

#include "duckdb/function/function_set.hpp"

namespace duckdb {

struct StExtentFun {
	static constexpr const char *Name = "st_extent";
	static constexpr const char *Parameters = "geometry";
	static constexpr const char *Description = "Returns the extent of a geometry";
	static constexpr const char *Example = "st_extent(geometry)";
	static constexpr const char *Categories = "";

	static ScalarFunction GetFunction();
};

struct StIntersectExtentFun {
	static constexpr const char *Name = "st_intersect_extent";
	static constexpr const char *Parameters = "geometry,geometry";
	static constexpr const char *Description = "Returns if two geometries extents intersect";
	static constexpr const char *Example = "st_intersect_extent(geometry)";
	static constexpr const char *Categories = "";

	static ScalarFunction GetFunction();
};

struct StIntersectExtentFunAlias {
	using ALIAS = StIntersectExtentFun;

	static constexpr const char *Name = "&&";
};

} // namespace duckdb
