run:
  uv run capigen c -o ../src/include/duckdb_v2.h

watch:
  watchexec --restart --exts yaml,py,j2,json --clear --watch src --watch api_spec -- uv run capigen c -o ../src/include/duckdb_v2.h

lint:
  uvx ruff check

typecheck:
  uvx ty check

test *args:
  uv run --group dev pytest {{args}}

check:
  just lint typecheck

format:
  uvx ruff format
