// AUTO-GENERATED by capigen bridge adapter -- do not edit.
// Re-run: capigen bridge --spec-dir api_spec/v2 --scan-dir src/main/capi_v2 -o src/main/capi_v2/capi_v2_stubs.cpp

#include "capi_v2_internal.hpp"
