//===----------------------------------------------------------------------===//
//
//                         DuckDB
//
// duckdb_v2.h
//
//
//===----------------------------------------------------------------------===//
//
// !!!!!!!
// WARNING: this file is autogenerated, manual changes will be overwritten
// !!!!!!!

#pragma once

#include <stdbool.h>
#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DUCKDB_C_API
#ifdef _WIN32
#ifdef DUCKDB_STATIC_BUILD
#define DUCKDB_C_API
#elif defined(DUCKDB_BUILD_LIBRARY) && !defined(DUCKDB_BUILD_LOADABLE_EXTENSION)
#define DUCKDB_C_API __declspec(dllexport)
#else
#define DUCKDB_C_API __declspec(dllimport)
#endif
#else
#if defined(__GNUC__) || defined(__clang__)
#define DUCKDB_C_API __attribute__((visibility("default")))
#else
#define DUCKDB_C_API
#endif
#endif
#endif

#ifndef DUCKDB_EXTENSION_API
#ifdef _WIN32
#ifdef DUCKDB_STATIC_BUILD
#define DUCKDB_EXTENSION_API
#else
#define DUCKDB_EXTENSION_API __declspec(dllexport)
#endif
#else
#if defined(__GNUC__) || defined(__clang__)
#define DUCKDB_EXTENSION_API __attribute__((visibility("default")))
#else
#define DUCKDB_EXTENSION_API
#endif
#endif
#endif

#if defined(__GNUC__) || defined(__clang__)
#define DUCKDB_DEPRECATED                                                                                              \
	__attribute__((deprecated("This function is deprecated and will be removed in a future version.")))
#elif defined(_MSC_VER)
#define DUCKDB_DEPRECATED __declspec(deprecated("This function is deprecated and will be removed in a future version."))
#else
#define DUCKDB_DEPRECATED
#endif

//===--------------------------------------------------------------------===//
// General type definitions
//===--------------------------------------------------------------------===//

//! DuckDB's index type.
typedef uint64_t idx_t;

/* ============================================================================
 * MODULE: common
 * ============================================================================ */

/* --- Types for common --- */
typedef void *duckdb_v2_database_ptr;
typedef void *duckdb_v2_connection_ptr;
typedef void *duckdb_v2_config_ptr;
typedef void *duckdb_v2_instance_cache_ptr;
typedef void *duckdb_v2_client_context_ptr;
typedef void *duckdb_v2_prepared_statement_ptr;
typedef void *duckdb_v2_result_ptr;
typedef void *duckdb_v2_data_chunk_ptr;
typedef void *duckdb_v2_vector_ptr;
typedef void *duckdb_v2_logical_type_ptr;
typedef void *duckdb_v2_value_ptr;
typedef void *duckdb_v2_error_info_ptr;
typedef uint32_t duckdb_v2_error_kind_t;
typedef uint32_t duckdb_v2_error_code_t;
typedef duckdb_v2_error_code_t DUCKDB_V2_API_CALL_t;

/* --- Enums for common --- */
typedef enum DUCKDB_V2_TYPE {
	/* Represents an invalid or uninitialized type. */
	DUCKDB_V2_TYPE_INVALID = 0,
	/* bool */
	DUCKDB_V2_TYPE_BOOLEAN = 1,
	/* int8_t */
	DUCKDB_V2_TYPE_TINYINT = 2,
	DUCKDB_V2_TYPE_SMALLINT = 3,
} DUCKDB_V2_TYPE;

/* --- Structs for common --- */

/* --- Constants for common --- */

/* --- Error Codes for common --- */

/* --- Function pointer typedefs for common --- */

/* --- Functions for common --- */

/* ============================================================================
 * MODULE: errors
 * ============================================================================ */

/* --- Types for errors --- */

/* --- Enums for errors --- */

/* --- Structs for errors --- */

/* --- Constants for errors --- */
#define DUCKDB_V2_API_ERROR 0xFFFFFFFF

/* --- Error Codes for errors --- */
#define DUCKDB_V2_ERROR_NONE              ((0 << 16) | 0)
#define DUCKDB_V2_ERROR_IO_FILE_NOT_FOUND ((1 << 16) | 1)
#define DUCKDB_V2_ERROR_IO_READ_FAILURE   ((1 << 16) | 2)
#define DUCKDB_V2_ERROR_EOF               ((2 << 16) | 1)
#define DUCKDB_V2_ERROR_INVALID_INPUT     ((2 << 16) | 2)
#define DUCKDB_V2_ERROR_INVALID_PARAMETER ((2 << 16) | 3)

/* --- Function pointer typedefs for errors --- */

/* --- Functions for errors --- */

/* ============================================================================
 * MODULE: configuration
 * ============================================================================ */

/* --- Types for configuration --- */

/* --- Enums for configuration --- */

/* --- Structs for configuration --- */

/* --- Constants for configuration --- */

/* --- Error Codes for configuration --- */

/* --- Function pointer typedefs for configuration --- */

/* --- Functions for configuration --- */
/*!
 * Initializes an empty configuration object.
 * @param out_config The result configuration object.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_create_config(duckdb_v2_config_ptr *out_config,
                                                          duckdb_v2_error_info_ptr *err);
/*!
 * Returns the total number of configuration options available.
 * @param out_count The number of config options available.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_config_count(idx_t *out_count, duckdb_v2_error_info_ptr *err);
/*!
 * Obtains the name and description of a specific configuration option.
 * @param index The index of the configuration option.
 * @param out_name The name of the configuration flag.
 * @param out_description A description of the configuration flag.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_get_config_flag(idx_t index, char **out_name, char **out_description,
                                                            duckdb_v2_error_info_ptr *err);
/*!
 * Sets the specified option for the specified configuration.
 * @param config The configuration object to set the option on.
 * @param name The name of the configuration flag to set.
 * @param option The value to set the configuration flag to.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_set_config(duckdb_v2_config_ptr config, const char *name,
                                                       const char *option, duckdb_v2_error_info_ptr *err);
/*!
 * Destroys the specified configuration object.
 * @param config The configuration object to destroy.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_destroy_config(duckdb_v2_config_ptr *config, duckdb_v2_error_info_ptr *err);

/* ============================================================================
 * MODULE: data_chunk
 * ============================================================================ */

/* --- Types for data_chunk --- */

/* --- Enums for data_chunk --- */

/* --- Structs for data_chunk --- */

/* --- Constants for data_chunk --- */

/* --- Error Codes for data_chunk --- */

/* --- Function pointer typedefs for data_chunk --- */

/* --- Functions for data_chunk --- */
/*!
 * Destroys the data chunk and de-allocates all memory.
 * @param chunk The data chunk to destroy.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_destroy_data_chunk(duckdb_v2_data_chunk_ptr *chunk,
                                                               duckdb_v2_error_info_ptr *err);
/*!
 * Retrieves the vector at the specified column index.
 * @param chunk The data chunk to get the data from.
 * @param col_idx The column index.
 * @param out_vector The vector at the specified column index.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_data_chunk_get_vector(duckdb_v2_data_chunk_ptr chunk, idx_t col_idx,
                                                                  duckdb_v2_vector_ptr *out_vector,
                                                                  duckdb_v2_error_info_ptr *err);
/*!
 * Retrieves the current number of tuples in a data chunk.
 * @param chunk The data chunk.
 * @param out_size The number of tuples in the data chunk.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_data_chunk_get_size(duckdb_v2_data_chunk_ptr chunk, idx_t *out_size,
                                                                duckdb_v2_error_info_ptr *err);

/* ============================================================================
 * MODULE: database
 * ============================================================================ */

/* --- Types for database --- */

/* --- Enums for database --- */

/* --- Structs for database --- */

/* --- Constants for database --- */

/* --- Error Codes for database --- */

/* --- Function pointer typedefs for database --- */

/* --- Functions for database --- */
/*!
 * Creates a new database or opens an existing database file.
 * @param path Path to the database file on disk. Both nullptr and :memory: open an in-memory database.
 * @param out_database The result database object.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_open(const char *path, duckdb_v2_database_ptr *out_database,
                                                 duckdb_v2_error_info_ptr *err);
/*!
 * Extended version of duckdb_open with configuration support.
 * @param path Path to the database file on disk. Both nullptr and :memory: open an in-memory database.
 * @param config Optional configuration used to start up the database.
 * @param out_database The result database object.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_open_ext(const char *path, duckdb_v2_config_ptr config,
                                                     duckdb_v2_database_ptr *out_database,
                                                     duckdb_v2_error_info_ptr *err);
/*!
 * Closes the specified database and de-allocates all memory.
 * @param database The database object to shut down.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_close(duckdb_v2_database_ptr *database, duckdb_v2_error_info_ptr *err);
/*!
 * Opens a connection to a database.
 * @param database The database file to connect to.
 * @param out_connection The result connection object.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_connect(duckdb_v2_database_ptr database,
                                                    duckdb_v2_connection_ptr *out_connection,
                                                    duckdb_v2_error_info_ptr *err);
/*!
 * Closes the specified connection and de-allocates all memory.
 * @param connection The connection to close.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_disconnect(duckdb_v2_connection_ptr *connection,
                                                       duckdb_v2_error_info_ptr *err);
/*!
 * Retrieves the client context of the connection.
 * @param connection The connection.
 * @param out_context The client context. Must be destroyed with duckdb_destroy_client_context.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_connection_get_client_context(duckdb_v2_connection_ptr connection,
                                                                          duckdb_v2_client_context_ptr *out_context,
                                                                          duckdb_v2_error_info_ptr *err);
/*!
 * Returns the connection id of the client context.
 * @param client_context The client context.
 * @param out_connection_id The connection id.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_client_context_get_connection_id(
    duckdb_v2_client_context_ptr client_context, idx_t *out_connection_id, duckdb_v2_error_info_ptr *err);
/*!
 * Destroys the client context and deallocates its memory.
 * @param client_context The client context to destroy.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_destroy_client_context(duckdb_v2_client_context_ptr *client_context,
                                                                   duckdb_v2_error_info_ptr *err);
/*!
 * Creates a new database instance cache.
 * @param out_instance_cache The database instance cache.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_create_instance_cache(duckdb_v2_instance_cache_ptr *out_instance_cache,
                                                                  duckdb_v2_error_info_ptr *err);
/*!
 * Creates or retrieves a database instance from the cache.
 * @param instance_cache The instance cache.
 * @param path Path to the database file on disk.
 * @param config Optional configuration used to create the database.
 * @param out_database The resulting cached database.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_get_or_create_from_cache(duckdb_v2_instance_cache_ptr instance_cache,
                                                                     const char *path, duckdb_v2_config_ptr config,
                                                                     duckdb_v2_database_ptr *out_database,
                                                                     duckdb_v2_error_info_ptr *err);
/*!
 * Destroys an existing database instance cache.
 * @param instance_cache The instance cache to destroy.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_destroy_instance_cache(duckdb_v2_instance_cache_ptr *instance_cache,
                                                                   duckdb_v2_error_info_ptr *err);
/*!
 * Returns the version of the linked DuckDB library.
 * @param out_version The version string.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_library_version(char **out_version, duckdb_v2_error_info_ptr *err);

/* ============================================================================
 * MODULE: error
 * ============================================================================ */

/* --- Types for error --- */

/* --- Enums for error --- */

/* --- Structs for error --- */

/* --- Constants for error --- */

/* --- Error Codes for error --- */

/* --- Function pointer typedefs for error --- */

/* --- Functions for error --- */
/*!
* Retrieves the error message associated with an error info handle.
* Returns a borrowed pointer to the info's null-terminated error message.
The pointer is owned by the library and is valid until the info is
destroyed; callers must not free it and must not read it after the
info has been destroyed.

* @param info The error info handle to query.
* @param out_message Borrowed pointer to the null-terminated message. Owned by the library; must not be freed.
* @param err Optional. On failure, receives an opaque info handle the caller must destroy via
duckdb_v2_destroy_error_info.
* @return DUCKDB_V2_API_CALL_t
*/
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_error_info_get_message(duckdb_v2_error_info_ptr info,
                                                                   const char **out_message,
                                                                   duckdb_v2_error_info_ptr *err);
/*!
* Destroys an error info handle and frees its resources.
* Null-safe: calling with a null handle or a null pointer-to-handle is a
no-op and returns DUCKDB_V2_ERROR_NONE. On return, `*info` is set to
nullptr. Safe to call on any info returned by the library.

* @param info The error info handle to destroy. Set to nullptr on return.
* @param err Optional. On failure, receives an opaque info handle the caller must destroy via
duckdb_v2_destroy_error_info.
* @return DUCKDB_V2_API_CALL_t
*/
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_destroy_error_info(duckdb_v2_error_info_ptr *info,
                                                               duckdb_v2_error_info_ptr *err);

/* ============================================================================
 * MODULE: helpers
 * ============================================================================ */

/* --- Types for helpers --- */

/* --- Enums for helpers --- */

/* --- Structs for helpers --- */
typedef struct {
	int32_t days;
} duckdb_v2_date;
typedef struct {
	int32_t year;
	int8_t month;
	int8_t day;
} duckdb_v2_date_struct;
typedef struct {
	int64_t micros;
} duckdb_v2_time;
typedef struct {
	int8_t hour;
	int8_t min;
	int8_t sec;
	int32_t micros;
} duckdb_v2_time_struct;
typedef struct {
	uint64_t bits;
} duckdb_v2_time_tz;
typedef struct {
	duckdb_v2_time_struct time;
	int32_t offset;
} duckdb_v2_time_tz_struct;
typedef struct {
	int64_t micros;
} duckdb_v2_timestamp;
typedef struct {
	int32_t months;
	int32_t days;
	int64_t micros;
} duckdb_v2_interval;
typedef struct {
	uint64_t lower;
	int64_t upper;
} duckdb_v2_hugeint;
typedef struct {
	uint64_t lower;
	uint64_t upper;
} duckdb_v2_uhugeint;
typedef struct {
	uint8_t width;
	uint8_t scale;
	duckdb_v2_hugeint value;
} duckdb_v2_decimal;
typedef struct {
	uint64_t offset;
	uint64_t length;
} duckdb_v2_list_entry;
typedef struct {
	uint8_t *data;
	idx_t size;
	bool is_negative;
} duckdb_v2_bignum;
typedef struct {
	uint32_t length;
	char *data;
} duckdb_v2_string_t;

/* --- Constants for helpers --- */

/* --- Error Codes for helpers --- */

/* --- Function pointer typedefs for helpers --- */

/* --- Functions for helpers --- */
/*!
 * Free memory allocated by duckdb_malloc or returned by other functions.
 * @param ptr The memory region to de-allocate.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_free(void *ptr, duckdb_v2_error_info_ptr *err);
/*!
 * Decompose a duckdb_v2_date into year, month, and day.
 * @param date The date object.
 * @param out_result The decomposed date struct.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_from_date(duckdb_v2_date date, duckdb_v2_date_struct *out_result,
                                                      duckdb_v2_error_info_ptr *err);
/*!
 * Re-compose a duckdb_v2_date from year, month, and day.
 * @param date The year, month and date stored in a duckdb_v2_date_struct.
 * @param out_result The duckdb_v2_date element.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_to_date(duckdb_v2_date_struct date, duckdb_v2_date *out_result,
                                                    duckdb_v2_error_info_ptr *err);
/*!
 * Decompose a duckdb_v2_time into hour, minute, second, and microsecond.
 * @param time The time object.
 * @param out_result The decomposed time struct.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_from_time(duckdb_v2_time time, duckdb_v2_time_struct *out_result,
                                                      duckdb_v2_error_info_ptr *err);
/*!
 * Re-compose a duckdb_v2_time from hour, minute, second, and microsecond.
 * @param time The time struct.
 * @param out_result The duckdb_v2_time element.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_to_time(duckdb_v2_time_struct time, duckdb_v2_time *out_result,
                                                    duckdb_v2_error_info_ptr *err);
/*!
 * Create a duckdb_v2_time_tz from micros and a timezone offset.
 * @param micros The microsecond component.
 * @param offset The timezone offset component.
 * @param out_result The duckdb_v2_time_tz element.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_create_time_tz(int64_t micros, int32_t offset,
                                                           duckdb_v2_time_tz *out_result,
                                                           duckdb_v2_error_info_ptr *err);
/*!
 * Decompose a TIME_TZ into micros and a timezone offset.
 * @param time_tz The time_tz object.
 * @param out_result The decomposed time_tz struct.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_from_time_tz(duckdb_v2_time_tz time_tz,
                                                         duckdb_v2_time_tz_struct *out_result,
                                                         duckdb_v2_error_info_ptr *err);
/*!
 * Re-compose a duckdb_v2_timestamp from a duckdb_v2_timestamp_struct.
 * @param micros The microsecond component.
 * @param out_result The duckdb_v2_timestamp element.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_create_timestamp(int64_t micros, duckdb_v2_timestamp *out_result,
                                                             duckdb_v2_error_info_ptr *err);
/*!
 * Create a UUID value.
 * @param out_result The UUID represented as a hugeint.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_create_uuid(duckdb_v2_hugeint *out_result, duckdb_v2_error_info_ptr *err);

/* ============================================================================
 * MODULE: logical_type
 * ============================================================================ */

/* --- Types for logical_type --- */

/* --- Enums for logical_type --- */

/* --- Structs for logical_type --- */

/* --- Constants for logical_type --- */

/* --- Error Codes for logical_type --- */

/* --- Function pointer typedefs for logical_type --- */

/* --- Functions for logical_type --- */
/*!
 * Creates a logical type from a primitive duckdb_type.
 * @param type The primitive duckdb_type to create.
 * @param out_type The logical type. Must be destroyed with duckdb_destroy_logical_type.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_create_logical_type(uint32_t type, duckdb_v2_logical_type_ptr *out_type,
                                                                duckdb_v2_error_info_ptr *err);
/*!
 * Destroys the logical type and de-allocates all memory.
 * @param type The logical type to destroy.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_destroy_logical_type(duckdb_v2_logical_type_ptr *type,
                                                                 duckdb_v2_error_info_ptr *err);
/*!
 * Retrieves the duckdb_type enum of a logical type.
 * @param type The logical type.
 * @param out_type_id The duckdb_type id.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_get_type_id(duckdb_v2_logical_type_ptr type, uint32_t *out_type_id,
                                                        duckdb_v2_error_info_ptr *err);
/*!
 * Retrieves the width of a decimal type.
 * @param type The logical type object.
 * @param out_width The width of the decimal type.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_decimal_width(duckdb_v2_logical_type_ptr type, uint8_t *out_width,
                                                          duckdb_v2_error_info_ptr *err);
/*!
 * Retrieves the scale of a decimal type.
 * @param type The logical type object.
 * @param out_scale The scale of the decimal type.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_decimal_scale(duckdb_v2_logical_type_ptr type, uint8_t *out_scale,
                                                          duckdb_v2_error_info_ptr *err);
/*!
 * Retrieves the dictionary size of the enum type.
 * @param type The logical type object.
 * @param out_size The dictionary size of the enum type.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_enum_dictionary_size(duckdb_v2_logical_type_ptr type, uint32_t *out_size,
                                                                 duckdb_v2_error_info_ptr *err);
/*!
 * Retrieves the dictionary value at the specified position from the enum.
 * @param type The logical type object.
 * @param index The index in the dictionary.
 * @param out_value The string value. Must be freed with duckdb_free.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_enum_dictionary_value(duckdb_v2_logical_type_ptr type, idx_t index,
                                                                  char **out_value, duckdb_v2_error_info_ptr *err);
/*!
 * Retrieves the child type of a LIST type.
 * @param type The logical type, either LIST or MAP.
 * @param out_child_type The child type. Must be destroyed with duckdb_destroy_logical_type.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_list_type_child_type(duckdb_v2_logical_type_ptr type,
                                                                 duckdb_v2_logical_type_ptr *out_child_type,
                                                                 duckdb_v2_error_info_ptr *err);
/*!
 * Retrieves the child type of an ARRAY type.
 * @param type The logical type. Must be ARRAY.
 * @param out_child_type The child type. Must be destroyed with duckdb_destroy_logical_type.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_array_type_child_type(duckdb_v2_logical_type_ptr type,
                                                                  duckdb_v2_logical_type_ptr *out_child_type,
                                                                  duckdb_v2_error_info_ptr *err);
/*!
 * Retrieves the fixed array size of an ARRAY type.
 * @param type The logical type object.
 * @param out_size The fixed number of elements in the array type.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_array_type_array_size(duckdb_v2_logical_type_ptr type, idx_t *out_size,
                                                                  duckdb_v2_error_info_ptr *err);
/*!
 * Retrieves the key type of a MAP type.
 * @param type The logical type object.
 * @param out_key_type The key type. Must be destroyed with duckdb_destroy_logical_type.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_map_type_key_type(duckdb_v2_logical_type_ptr type,
                                                              duckdb_v2_logical_type_ptr *out_key_type,
                                                              duckdb_v2_error_info_ptr *err);
/*!
 * Retrieves the value type of a MAP type.
 * @param type The logical type object.
 * @param out_value_type The value type. Must be destroyed with duckdb_destroy_logical_type.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_map_type_value_type(duckdb_v2_logical_type_ptr type,
                                                                duckdb_v2_logical_type_ptr *out_value_type,
                                                                duckdb_v2_error_info_ptr *err);
/*!
 * Returns the number of children of a struct type.
 * @param type The logical type object.
 * @param out_count The number of children of the struct type.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_struct_type_child_count(duckdb_v2_logical_type_ptr type, idx_t *out_count,
                                                                    duckdb_v2_error_info_ptr *err);
/*!
 * Retrieves the name of a struct child.
 * @param type The logical type object.
 * @param index The child index.
 * @param out_name The name. Must be freed with duckdb_free.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_struct_type_child_name(duckdb_v2_logical_type_ptr type, idx_t index,
                                                                   char **out_name, duckdb_v2_error_info_ptr *err);
/*!
 * Retrieves the child type of a struct at the specified index.
 * @param type The logical type object.
 * @param index The child index.
 * @param out_child_type The child type. Must be destroyed with duckdb_destroy_logical_type.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_struct_type_child_type(duckdb_v2_logical_type_ptr type, idx_t index,
                                                                   duckdb_v2_logical_type_ptr *out_child_type,
                                                                   duckdb_v2_error_info_ptr *err);
/*!
 * Returns the number of members in a union type.
 * @param type The logical type (union) object.
 * @param out_count The number of union members.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_union_type_member_count(duckdb_v2_logical_type_ptr type, idx_t *out_count,
                                                                    duckdb_v2_error_info_ptr *err);
/*!
 * Retrieves the name of a union member.
 * @param type The logical type object.
 * @param index The member index.
 * @param out_name The name. Must be freed with duckdb_free.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_union_type_member_name(duckdb_v2_logical_type_ptr type, idx_t index,
                                                                   char **out_name, duckdb_v2_error_info_ptr *err);
/*!
 * Retrieves the child type of a union member at the specified index.
 * @param type The logical type object.
 * @param index The member index.
 * @param out_member_type The member type. Must be destroyed with duckdb_destroy_logical_type.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_union_type_member_type(duckdb_v2_logical_type_ptr type, idx_t index,
                                                                   duckdb_v2_logical_type_ptr *out_member_type,
                                                                   duckdb_v2_error_info_ptr *err);

/* ============================================================================
 * MODULE: prepared_statements
 * ============================================================================ */

/* --- Types for prepared_statements --- */

/* --- Enums for prepared_statements --- */

/* --- Structs for prepared_statements --- */

/* --- Constants for prepared_statements --- */

/* --- Error Codes for prepared_statements --- */

/* --- Function pointer typedefs for prepared_statements --- */

/* --- Functions for prepared_statements --- */
/*!
 * Create a prepared statement object from a query.
 * @param connection The connection object.
 * @param query The SQL query to prepare.
 * @param out_prepared_statement The resulting prepared statement object.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_prepare(duckdb_v2_connection_ptr connection, const char *query,
                                                    duckdb_v2_prepared_statement_ptr *out_prepared_statement,
                                                    duckdb_v2_error_info_ptr *err);
/*!
 * Closes the prepared statement and de-allocates all memory.
 * @param prepared_statement The prepared statement to destroy.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_destroy_prepare(duckdb_v2_prepared_statement_ptr *prepared_statement,
                                                            duckdb_v2_error_info_ptr *err);
/*!
 * Returns the error message associated with the prepared statement.
 * @param prepared_statement The prepared statement to obtain the error from.
 * @param out_error The error message, or nullptr if there is none.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_prepare_error(duckdb_v2_prepared_statement_ptr prepared_statement,
                                                          char **out_error, duckdb_v2_error_info_ptr *err);
/*!
 * Returns the number of parameters in the prepared statement.
 * @param prepared_statement The prepared statement.
 * @param out_count The number of parameters.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_nparams(duckdb_v2_prepared_statement_ptr prepared_statement,
                                                    idx_t *out_count, duckdb_v2_error_info_ptr *err);
/*!
 * Returns the name used to identify the parameter.
 * @param prepared_statement The prepared statement.
 * @param index The parameter index.
 * @param out_name The parameter name. Must be freed with duckdb_free.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_parameter_name(duckdb_v2_prepared_statement_ptr prepared_statement,
                                                           idx_t index, char **out_name, duckdb_v2_error_info_ptr *err);
/*!
 * Returns the parameter type for the parameter at the given index.
 * @param prepared_statement The prepared statement.
 * @param param_idx The parameter index.
 * @param out_type The parameter type.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_param_type(duckdb_v2_prepared_statement_ptr prepared_statement,
                                                       idx_t param_idx, uint32_t *out_type,
                                                       duckdb_v2_error_info_ptr *err);
/*!
 * Returns the logical type for the parameter at the given index.
 * @param prepared_statement The prepared statement.
 * @param param_idx The parameter index.
 * @param out_type The logical type. Must be destroyed with duckdb_destroy_logical_type.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_param_logical_type(duckdb_v2_prepared_statement_ptr prepared_statement,
                                                               idx_t param_idx, duckdb_v2_logical_type_ptr *out_type,
                                                               duckdb_v2_error_info_ptr *err);
/*!
 * Clear the params bound to the prepared statement.
 * @param prepared_statement The prepared statement.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_clear_bindings(duckdb_v2_prepared_statement_ptr prepared_statement,
                                                           duckdb_v2_error_info_ptr *err);
/*!
 * Returns the statement type of the prepared statement.
 * @param stmt The prepared statement.
 * @param out_type The statement type.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_prepared_statement_type(duckdb_v2_prepared_statement_ptr stmt,
                                                                    uint32_t *out_type, duckdb_v2_error_info_ptr *err);
/*!
 * Executes the prepared statement and returns a materialized query result.
 * @param prepared_statement The prepared statement to execute.
 * @param out_result The query result.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_execute_prepared(duckdb_v2_prepared_statement_ptr prepared_statement,
                                                             duckdb_v2_result_ptr *out_result,
                                                             duckdb_v2_error_info_ptr *err);
/*!
 * Binds a value to the prepared statement at the specified index.
 * @param prepared_statement The prepared statement.
 * @param param_idx The parameter index.
 * @param val The value to bind.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_bind_value(duckdb_v2_prepared_statement_ptr prepared_statement,
                                                       idx_t param_idx, duckdb_v2_value_ptr val,
                                                       duckdb_v2_error_info_ptr *err);
/*!
 * Retrieve the index of the parameter identified by name.
 * @param prepared_statement The prepared statement.
 * @param name The parameter name.
 * @param out_param_idx The parameter index.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_bind_parameter_index(duckdb_v2_prepared_statement_ptr prepared_statement,
                                                                 const char *name, idx_t *out_param_idx,
                                                                 duckdb_v2_error_info_ptr *err);
/*!
 * Binds a bool value to the prepared statement at the specified index.
 * @param prepared_statement The prepared statement.
 * @param param_idx The parameter index.
 * @param val The boolean value.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_bind_boolean(duckdb_v2_prepared_statement_ptr prepared_statement,
                                                         idx_t param_idx, bool val, duckdb_v2_error_info_ptr *err);
/*!
 * Binds an int8_t value to the prepared statement.
 * @param prepared_statement The prepared statement.
 * @param param_idx The parameter index.
 * @param val The int8_t value.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_bind_int8(duckdb_v2_prepared_statement_ptr prepared_statement,
                                                      idx_t param_idx, int8_t val, duckdb_v2_error_info_ptr *err);
/*!
 * Binds an int16_t value to the prepared statement.
 * @param prepared_statement The prepared statement.
 * @param param_idx The parameter index.
 * @param val The int16_t value.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_bind_int16(duckdb_v2_prepared_statement_ptr prepared_statement,
                                                       idx_t param_idx, int16_t val, duckdb_v2_error_info_ptr *err);
/*!
 * Binds an int32_t value to the prepared statement.
 * @param prepared_statement The prepared statement.
 * @param param_idx The parameter index.
 * @param val The int32_t value.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_bind_int32(duckdb_v2_prepared_statement_ptr prepared_statement,
                                                       idx_t param_idx, int32_t val, duckdb_v2_error_info_ptr *err);
/*!
 * Binds an int64_t value to the prepared statement.
 * @param prepared_statement The prepared statement.
 * @param param_idx The parameter index.
 * @param val The int64_t value.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_bind_int64(duckdb_v2_prepared_statement_ptr prepared_statement,
                                                       idx_t param_idx, int64_t val, duckdb_v2_error_info_ptr *err);
/*!
 * Binds a duckdb_v2_hugeint value to the prepared statement.
 * @param prepared_statement The prepared statement.
 * @param param_idx The parameter index.
 * @param val The hugeint value.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_bind_hugeint(duckdb_v2_prepared_statement_ptr prepared_statement,
                                                         idx_t param_idx, duckdb_v2_hugeint val,
                                                         duckdb_v2_error_info_ptr *err);
/*!
 * Binds a duckdb_v2_uhugeint value to the prepared statement.
 * @param prepared_statement The prepared statement.
 * @param param_idx The parameter index.
 * @param val The uhugeint value.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_bind_uhugeint(duckdb_v2_prepared_statement_ptr prepared_statement,
                                                          idx_t param_idx, duckdb_v2_uhugeint val,
                                                          duckdb_v2_error_info_ptr *err);
/*!
 * Binds a duckdb_v2_decimal value to the prepared statement.
 * @param prepared_statement The prepared statement.
 * @param param_idx The parameter index.
 * @param val The decimal value.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_bind_decimal(duckdb_v2_prepared_statement_ptr prepared_statement,
                                                         idx_t param_idx, duckdb_v2_decimal val,
                                                         duckdb_v2_error_info_ptr *err);
/*!
 * Binds a uint8_t value to the prepared statement.
 * @param prepared_statement The prepared statement.
 * @param param_idx The parameter index.
 * @param val The uint8_t value.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_bind_uint8(duckdb_v2_prepared_statement_ptr prepared_statement,
                                                       idx_t param_idx, uint8_t val, duckdb_v2_error_info_ptr *err);
/*!
 * Binds a uint16_t value to the prepared statement.
 * @param prepared_statement The prepared statement.
 * @param param_idx The parameter index.
 * @param val The uint16_t value.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_bind_uint16(duckdb_v2_prepared_statement_ptr prepared_statement,
                                                        idx_t param_idx, uint16_t val, duckdb_v2_error_info_ptr *err);
/*!
 * Binds a uint32_t value to the prepared statement.
 * @param prepared_statement The prepared statement.
 * @param param_idx The parameter index.
 * @param val The uint32_t value.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_bind_uint32(duckdb_v2_prepared_statement_ptr prepared_statement,
                                                        idx_t param_idx, uint32_t val, duckdb_v2_error_info_ptr *err);
/*!
 * Binds a uint64_t value to the prepared statement.
 * @param prepared_statement The prepared statement.
 * @param param_idx The parameter index.
 * @param val The uint64_t value.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_bind_uint64(duckdb_v2_prepared_statement_ptr prepared_statement,
                                                        idx_t param_idx, uint64_t val, duckdb_v2_error_info_ptr *err);
/*!
 * Binds a float value to the prepared statement.
 * @param prepared_statement The prepared statement.
 * @param param_idx The parameter index.
 * @param val The float value.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_bind_float(duckdb_v2_prepared_statement_ptr prepared_statement,
                                                       idx_t param_idx, float val, duckdb_v2_error_info_ptr *err);
/*!
 * Binds a double value to the prepared statement.
 * @param prepared_statement The prepared statement.
 * @param param_idx The parameter index.
 * @param val The double value.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_bind_double(duckdb_v2_prepared_statement_ptr prepared_statement,
                                                        idx_t param_idx, double val, duckdb_v2_error_info_ptr *err);
/*!
 * Binds a duckdb_v2_date value to the prepared statement.
 * @param prepared_statement The prepared statement.
 * @param param_idx The parameter index.
 * @param val The date value.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_bind_date(duckdb_v2_prepared_statement_ptr prepared_statement,
                                                      idx_t param_idx, duckdb_v2_date val,
                                                      duckdb_v2_error_info_ptr *err);
/*!
 * Binds a duckdb_v2_time value to the prepared statement.
 * @param prepared_statement The prepared statement.
 * @param param_idx The parameter index.
 * @param val The time value.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_bind_time(duckdb_v2_prepared_statement_ptr prepared_statement,
                                                      idx_t param_idx, duckdb_v2_time val,
                                                      duckdb_v2_error_info_ptr *err);
/*!
 * Binds a duckdb_v2_timestamp value to the prepared statement.
 * @param prepared_statement The prepared statement.
 * @param param_idx The parameter index.
 * @param val The timestamp value.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_bind_timestamp(duckdb_v2_prepared_statement_ptr prepared_statement,
                                                           idx_t param_idx, duckdb_v2_timestamp val,
                                                           duckdb_v2_error_info_ptr *err);
/*!
 * Binds a duckdb_v2_interval value to the prepared statement.
 * @param prepared_statement The prepared statement.
 * @param param_idx The parameter index.
 * @param val The interval value.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_bind_interval(duckdb_v2_prepared_statement_ptr prepared_statement,
                                                          idx_t param_idx, duckdb_v2_interval val,
                                                          duckdb_v2_error_info_ptr *err);
/*!
 * Binds a null-terminated varchar value to the prepared statement.
 * @param prepared_statement The prepared statement.
 * @param param_idx The parameter index.
 * @param val The null-terminated varchar value.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_bind_varchar(duckdb_v2_prepared_statement_ptr prepared_statement,
                                                         idx_t param_idx, const char *val,
                                                         duckdb_v2_error_info_ptr *err);
/*!
 * Binds a varchar value with explicit length to the prepared statement.
 * @param prepared_statement The prepared statement.
 * @param param_idx The parameter index.
 * @param val The varchar value.
 * @param length The length of the string in bytes.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_bind_varchar_length(duckdb_v2_prepared_statement_ptr prepared_statement,
                                                                idx_t param_idx, const char *val, idx_t length,
                                                                duckdb_v2_error_info_ptr *err);
/*!
 * Binds a blob value to the prepared statement.
 * @param prepared_statement The prepared statement.
 * @param param_idx The parameter index.
 * @param data The blob data.
 * @param length The length of the blob in bytes.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_bind_blob(duckdb_v2_prepared_statement_ptr prepared_statement,
                                                      idx_t param_idx, const void *data, idx_t length,
                                                      duckdb_v2_error_info_ptr *err);
/*!
 * Binds a NULL value to the prepared statement.
 * @param prepared_statement The prepared statement.
 * @param param_idx The parameter index.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_bind_null(duckdb_v2_prepared_statement_ptr prepared_statement,
                                                      idx_t param_idx, duckdb_v2_error_info_ptr *err);

/* ============================================================================
 * MODULE: query_result
 * ============================================================================ */

/* --- Types for query_result --- */

/* --- Enums for query_result --- */

/* --- Structs for query_result --- */

/* --- Constants for query_result --- */

/* --- Error Codes for query_result --- */

/* --- Function pointer typedefs for query_result --- */

/* --- Functions for query_result --- */
/*!
 * Executes a SQL query and stores the materialized result.
 * @param connection The connection to perform the query in.
 * @param query The SQL query to run.
 * @param out_result The query result.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_query(duckdb_v2_connection_ptr connection, const char *query,
                                                  duckdb_v2_result_ptr *out_result, duckdb_v2_error_info_ptr *err);
/*!
 * Closes the result and de-allocates all memory.
 * @param result The result to destroy.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_destroy_result(duckdb_v2_result_ptr *result, duckdb_v2_error_info_ptr *err);
/*!
 * Returns the column name of the specified column.
 * @param result The result object to fetch the column name from.
 * @param col The column index.
 * @param out_name The column name of the specified column.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_column_name(duckdb_v2_result_ptr result, idx_t col, char **out_name,
                                                        duckdb_v2_error_info_ptr *err);
/*!
 * Returns the column type of the specified column.
 * @param result The result object to fetch the column type from.
 * @param col The column index.
 * @param out_type The duckdb_type of the specified column.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_column_type(duckdb_v2_result_ptr result, idx_t col, uint32_t *out_type,
                                                        duckdb_v2_error_info_ptr *err);
/*!
 * Returns the logical column type of the specified column.
 * @param result The result object to fetch the column type from.
 * @param col The column index.
 * @param out_type The logical column type. Must be destroyed with duckdb_destroy_logical_type.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_column_logical_type(duckdb_v2_result_ptr result, idx_t col,
                                                                duckdb_v2_logical_type_ptr *out_type,
                                                                duckdb_v2_error_info_ptr *err);
/*!
 * Returns the number of columns present in the result.
 * @param result The result object.
 * @param out_column_count The number of columns.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_column_count(duckdb_v2_result_ptr result, idx_t *out_column_count,
                                                         duckdb_v2_error_info_ptr *err);
/*!
 * Returns the number of rows changed by the query.
 * @param result The result object.
 * @param out_rows_changed The number of rows changed.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_rows_changed(duckdb_v2_result_ptr result, idx_t *out_rows_changed,
                                                         duckdb_v2_error_info_ptr *err);
/*!
 * Returns the error message contained within the result.
 * @param result The result object to fetch the error from.
 * @param out_error The error message, or nullptr if there is none.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_result_error(duckdb_v2_result_ptr result, char **out_error,
                                                         duckdb_v2_error_info_ptr *err);
/*!
 * Returns the error type contained within the result.
 * @param result The result object to fetch the error type from.
 * @param out_error_type The error type of the result.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_result_error_type(duckdb_v2_result_ptr result, uint32_t *out_error_type,
                                                              duckdb_v2_error_info_ptr *err);
/*!
 * Returns the return type of the given result.
 * @param result The result object.
 * @param out_return_type The return type.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_result_return_type(duckdb_v2_result_ptr result, uint32_t *out_return_type,
                                                               duckdb_v2_error_info_ptr *err);
/*!
 * Fetches the next data chunk from a streaming result.
 * @param result The result object to fetch the chunk from.
 * @param out_chunk The resulting data chunk, or NULL when exhausted.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_fetch_chunk(duckdb_v2_result_ptr result,
                                                        duckdb_v2_data_chunk_ptr *out_chunk,
                                                        duckdb_v2_error_info_ptr *err);

/* ============================================================================
 * MODULE: scalar
 * ============================================================================ */

/* --- Types for scalar --- */
typedef void *duckdb_v2_scalar_func_ptr;
typedef void *duckdb_v2_scalar_func_bind_args_ptr;
typedef void *duckdb_v2_scalar_func_init_args_ptr;
typedef void *duckdb_v2_scalar_func_exec_args_ptr;

/* --- Enums for scalar --- */

/* --- Structs for scalar --- */

/* --- Constants for scalar --- */

/* --- Error Codes for scalar --- */

/* --- Function pointer typedefs for scalar --- */
typedef void (*duckdb_v2_scalar_func_bind_cb)(duckdb_v2_scalar_func_bind_args_ptr args);
typedef void (*duckdb_v2_scalar_func_init_cb)(duckdb_v2_scalar_func_init_args_ptr args);
typedef void (*duckdb_v2_scalar_func_exec_cb)(duckdb_v2_scalar_func_exec_args_ptr args);

/* --- Functions for scalar --- */
/*!
 * Get input chunk for scalar function execution
 * @param args
 * @param out_input
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_scalar_function_exec_get_input(duckdb_v2_scalar_func_exec_args_ptr args,
                                                                           duckdb_v2_data_chunk_ptr *out_input,
                                                                           duckdb_v2_error_info_ptr *err);
/*!
 * Get result vector for scalar function execution
 * @param args
 * @param out_result
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_scalar_function_exec_get_result(duckdb_v2_scalar_func_exec_args_ptr args,
                                                                            duckdb_v2_vector_ptr *out_result,
                                                                            duckdb_v2_error_info_ptr *err);
/*!
 * Create a scalar function object
 * @param out_function
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_scalar_function_create(duckdb_v2_scalar_func_ptr *out_function,
                                                                   duckdb_v2_error_info_ptr *err);
/*!
 * Set the bind function for a scalar function
 * @param function
 * @param bind_func
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_scalar_function_set_bind(duckdb_v2_scalar_func_ptr function,
                                                                     duckdb_v2_scalar_func_bind_cb bind_func,
                                                                     duckdb_v2_error_info_ptr *err);
/*!
 * Register a scalar function
 * @param function
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_scalar_function_register(duckdb_v2_scalar_func_ptr function,
                                                                     duckdb_v2_error_info_ptr *err);

/* ============================================================================
 * MODULE: type_value
 * ============================================================================ */

/* --- Types for type_value --- */
typedef void *duckdb_v2_type_ptr;
typedef void *duckdb_v2_type_info_ptr;
typedef void *duckdb_v2_value_info_ptr;

/* --- Enums for type_value --- */
typedef enum DUCKDB_V2_KIND {
	DUCKDB_V2_KIND_INTEGER = 1,
	DUCKDB_V2_KIND_STRUCT = 2,
} DUCKDB_V2_KIND;

/* --- Structs for type_value --- */

/* --- Constants for type_value --- */

/* --- Error Codes for type_value --- */

/* --- Function pointer typedefs for type_value --- */

/* --- Functions for type_value --- */
/*!
 * Create a mutable type info builder
 * @param info
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_type_info_create(duckdb_v2_type_info_ptr *info,
                                                             duckdb_v2_error_info_ptr *err);
/*!
 * Destroy a type info builder
 * @param info
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_type_info_delete(duckdb_v2_type_info_ptr *info,
                                                             duckdb_v2_error_info_ptr *err);
/*!
 * Set the alias name of the type to be created
 * @param info
 * @param name
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_type_info_set_name(duckdb_v2_type_info_ptr info, const char *name,
                                                               duckdb_v2_error_info_ptr *err);
/*!
 * Add a named type parameter (e.g. for STRUCT/LIST/MAP)
 * @param info
 * @param name
 * @param value
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_type_info_add_type(duckdb_v2_type_info_ptr info, const char *name,
                                                               duckdb_v2_type_ptr value, duckdb_v2_error_info_ptr *err);
/*!
 * Add a named value parameter (e.g. for DECIMAL precision/scale)
 * @param info
 * @param name
 * @param value
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_type_info_add_value(duckdb_v2_type_info_ptr info, const char *name,
                                                                duckdb_v2_value_ptr value,
                                                                duckdb_v2_error_info_ptr *err);
/*!
 * Create a type from a kind and optional type info (NULL for primitives)
 * @param kind
 * @param info
 * @param type
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_type_create_from_info(DUCKDB_V2_KIND kind, duckdb_v2_type_info_ptr info,
                                                                  duckdb_v2_type_ptr *type,
                                                                  duckdb_v2_error_info_ptr *err);
/*!
 * Create a type from a string representation
 * @param text
 * @param type
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_type_create_from_text(const char *text, duckdb_v2_type_ptr *type,
                                                                  duckdb_v2_error_info_ptr *err);
/*!
 * Delete a type object
 * @param type
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_type_delete(duckdb_v2_type_ptr *type, duckdb_v2_error_info_ptr *err);
/*!
 * Get the logical type id
 * @param type
 * @param kind
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_type_get_kind(duckdb_v2_type_ptr type, DUCKDB_V2_KIND *kind,
                                                          duckdb_v2_error_info_ptr *err);
/*!
 * Get the name/alias of the type
 * @param type
 * @param name
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_type_get_name(duckdb_v2_type_ptr type, const char **name,
                                                          duckdb_v2_error_info_ptr *err);
/*!
 * Get the full text representation of the type
 * @param type
 * @param text
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_type_get_text(duckdb_v2_type_ptr type, const char **text,
                                                          duckdb_v2_error_info_ptr *err);
/*!
 * Get the number of type parameters
 * @param type
 * @param out_count
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_type_get_param_count(duckdb_v2_type_ptr type, uint64_t *out_count,
                                                                 duckdb_v2_error_info_ptr *err);
/*!
 * Get a type parameter as a value by index
 * @param type
 * @param index
 * @param value
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_type_get_param_value(duckdb_v2_type_ptr type, uint64_t index,
                                                                 duckdb_v2_value_ptr *value,
                                                                 duckdb_v2_error_info_ptr *err);
/*!
 * Get a type parameter as a type by index
 * @param type
 * @param index
 * @param out_type
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_type_get_param_type(duckdb_v2_type_ptr type, uint64_t index,
                                                                duckdb_v2_type_ptr *out_type,
                                                                duckdb_v2_error_info_ptr *err);
/*!
 * Get the name of a type parameter by index
 * @param type
 * @param index
 * @param name
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_type_get_param_name(duckdb_v2_type_ptr type, uint64_t index,
                                                                const char **name, duckdb_v2_error_info_ptr *err);
/*!
 * Create a value from a type and raw data pointer
 * @param type
 * @param data Raw data pointer, or NULL for NULL values
 * @param value
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_value_create_from_type(duckdb_v2_type_ptr type, void *data,
                                                                   duckdb_v2_value_ptr *value,
                                                                   duckdb_v2_error_info_ptr *err);
/*!
 * Create a value from a kind and raw data pointer (helper for primitives)
 * @param kind
 * @param data
 * @param value
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_value_create_from_kind(DUCKDB_V2_KIND kind, void *data,
                                                                   duckdb_v2_value_ptr *value,
                                                                   duckdb_v2_error_info_ptr *err);
/*!
 * Delete a value object
 * @param value
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_value_delete(duckdb_v2_value_ptr *value, duckdb_v2_error_info_ptr *err);
/*!
 * Create a mutable value info builder
 * @param info
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_value_info_create(duckdb_v2_value_info_ptr *info,
                                                              duckdb_v2_error_info_ptr *err);
/*!
 * Set the type of the value being built
 * @param info
 * @param type
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_value_info_add_type(duckdb_v2_value_info_ptr info, duckdb_v2_type_ptr type,
                                                                duckdb_v2_error_info_ptr *err);
/*!
 * Add a child value to the value being built
 * @param info
 * @param value
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_value_info_add_value(duckdb_v2_value_info_ptr info,
                                                                 duckdb_v2_value_ptr value,
                                                                 duckdb_v2_error_info_ptr *err);
/*!
 * Destroy a value info builder
 * @param info
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_value_info_delete(duckdb_v2_value_info_ptr *info,
                                                              duckdb_v2_error_info_ptr *err);
/*!
 * Get the type of a value
 * @param value
 * @param type
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_value_get_type(duckdb_v2_value_ptr value, duckdb_v2_type_ptr *type,
                                                           duckdb_v2_error_info_ptr *err);
/*!
 * Get the raw data of a value (error if NULL)
 * @param value
 * @param data Buffer to receive the raw value data
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_value_get_data(duckdb_v2_value_ptr value, void *data,
                                                           duckdb_v2_error_info_ptr *err);
/*!
 * Check if a value is NULL (returns 0 if not null, 1 if null)
 * @param value
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_value_get_null(duckdb_v2_value_ptr value, duckdb_v2_error_info_ptr *err);
/*!
 * Get a nested child value by index (for complex types)
 * @param value
 * @param index
 * @param item
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_value_get_child(duckdb_v2_value_ptr value, uint64_t index,
                                                            duckdb_v2_value_ptr *item, duckdb_v2_error_info_ptr *err);

/* ============================================================================
 * MODULE: value
 * ============================================================================ */

/* --- Types for value --- */

/* --- Enums for value --- */

/* --- Structs for value --- */

/* --- Constants for value --- */

/* --- Error Codes for value --- */

/* --- Function pointer typedefs for value --- */

/* --- Functions for value --- */
/*!
 * Destroys the value and de-allocates all memory.
 * @param value The value to destroy.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_destroy_value(duckdb_v2_value_ptr *value, duckdb_v2_error_info_ptr *err);

/* ============================================================================
 * MODULE: vector
 * ============================================================================ */

/* --- Types for vector --- */

/* --- Enums for vector --- */

/* --- Structs for vector --- */

/* --- Constants for vector --- */

/* --- Error Codes for vector --- */

/* --- Function pointer typedefs for vector --- */

/* --- Functions for vector --- */
/*!
 * Retrieves the data pointer of the vector.
 * @param vector The vector to get the data from.
 * @param out_data The data pointer.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_vector_get_data(duckdb_v2_vector_ptr vector, void **out_data,
                                                            duckdb_v2_error_info_ptr *err);
/*!
 * Retrieves the validity mask pointer of the vector.
 * @param vector The vector to get the data from.
 * @param out_validity The pointer to the validity mask, or NULL if no validity mask is present.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_vector_get_validity(duckdb_v2_vector_ptr vector, uint64_t **out_validity,
                                                                duckdb_v2_error_info_ptr *err);
/*!
 * Returns whether or not a row is valid in the given validity mask.
 * @param validity The validity mask, as obtained through duckdb_v2_vector_get_validity.
 * @param row The row index.
 * @param out_valid True if the row is valid, false otherwise.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_validity_row_is_valid(uint64_t *validity, idx_t row, bool *out_valid,
                                                                  duckdb_v2_error_info_ptr *err);
/*!
 * Retrieves the child vector of a list vector.
 * @param vector The list vector.
 * @param out_child The child vector.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_list_vector_get_child(duckdb_v2_vector_ptr vector,
                                                                  duckdb_v2_vector_ptr *out_child,
                                                                  duckdb_v2_error_info_ptr *err);
/*!
 * Retrieves the child vector of a struct vector.
 * @param vector The struct vector.
 * @param index The child index.
 * @param out_child The child vector.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_struct_vector_get_child(duckdb_v2_vector_ptr vector, idx_t index,
                                                                    duckdb_v2_vector_ptr *out_child,
                                                                    duckdb_v2_error_info_ptr *err);
/*!
 * Retrieves the child vector of an array vector.
 * @param vector The array vector.
 * @param out_child The child vector.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_array_vector_get_child(duckdb_v2_vector_ptr vector,
                                                                   duckdb_v2_vector_ptr *out_child,
                                                                   duckdb_v2_error_info_ptr *err);
/*!
 * Whether or not the duckdb_v2_string_t value is inlined.
 * @param string The string value.
 * @param out_inlined True if the string is inlined.
 * @param err Optional. On failure, receives an opaque info handle the caller must destroy via
 * duckdb_v2_destroy_error_info.
 * @return DUCKDB_V2_API_CALL_t
 */
DUCKDB_C_API DUCKDB_V2_API_CALL_t duckdb_v2_string_is_inlined(duckdb_v2_string_t string, bool *out_inlined,
                                                              duckdb_v2_error_info_ptr *err);

#ifdef __cplusplus
}
#endif
